version: '3.7'

services:
  localstack:
    image: docker.io/localstack/localstack:0.13.3.3
    ports:
      - 8566:4566
    environment:
      SERVICES: s3

  verdaccio:
    image: docker.io/verdaccio/verdaccio:5.8.0
    ports:
      - 4873:4873
