#!/usr/bin/env bash
set -eu

clj-kondo --lint bases/ components/ projects/ src/ test/ "$@" ||
  (set -eu
   echo
   echo "!! fix linter warnings or"
   echo "!! (1) wrap offending form in #_{:clj-kondo/ignore [...]} "
   echo "!! (2) update .clj-kondo/config.edn"
   echo
   exit 1)
