#!/bin/bash
set -eu

if [ ! -e "scripts/clj-kondo" ] ; then
  echo -n "Installing clj-kondo [ ./scripts/clj-kondo ] ... "
  ./scripts/install-clj-kondo --dir $PWD/scripts > /dev/null
  echo "done"
fi

./scripts/clj-kondo --lint src/ test/ "$@"
