#!/bin/bash
set -eu

backup_dir=/data/sysrev/backups
date_string=$(date +%F_%H-%M-%S)
fname="sysrev-${date_string}.pgdumpc"
options="-T schema_version"

cd "$backup_dir"
pg_dump -h localhost -p 5470 -U postgres -Fc $options sysrev > "$fname"
echo "saved backup to $fname"
scp ./"$fname" insilica@insilica-ws-1.ddns.net:/data/backups/sysrev/"$fname" || true
