#!/bin/bash
set -eu

dir=/data/sysrev

# $dir/scripts/receive-client && true
# $dir/scripts/receive-server && true

echo $dir/deploy/deploy-done.client | entr $dir/scripts/receive-client &
echo $dir/deploy/deploy-done.server | entr $dir/scripts/receive-server &

exit 0
