#!/bin/bash
set -eu

host=$(hostname)
backup_dir=/data/sysrev/backups
date_string=$(date +%F_%H-%M-%S)
fname="sysrev-${date_string}.pgdumpc"
options="--exclude-table-data=article_similarity"

cd "$backup_dir"
pg_dump -U postgres -Fc $options sysrev > "$fname"
echo "$host: saved backup to $fname"
scp -i $HOME/.ssh/id_rsa.insilica ./"$fname" insilica@insilica-ws-1.ddns.net:/data/backups/"$host"/"$fname" || true
