(ns sysrev.test.all
  (:require sysrev.test.core
            sysrev.test.import
            sysrev.test.api
            sysrev.test.etaoin.dev-settings
            sysrev.test.browser.core
            sysrev.test.browser.annotation-label
            sysrev.test.browser.group-labels
            sysrev.test.browser.simple
            sysrev.test.browser.sources
            sysrev.test.browser.new-project
            sysrev.test.browser.orgs
            sysrev.test.browser.plans
            sysrev.test.browser.project-articles
            sysrev.test.browser.project-compensation
            sysrev.test.browser.pubmed
            sysrev.test.browser.review-articles
            sysrev.test.browser.search
            sysrev.test.browser.markdown
            sysrev.test.browser.review-settings
            sysrev.test.browser.label-settings
            sysrev.test.browser.user-profiles
            sysrev.test.browser.json-viewer
            sysrev.test.browser.clone
            sysrev.test.browser.blinding
            sysrev.test.browser.project-users
            sysrev.test.graphql.query
            sysrev.test.web.routes.api.handlers
            sysrev.test.web.routes.project))
