#!/bin/bash
set -eux

echo "Preparing build environment"

./setup.sh

lein clean

echo "Compiling CLJS project"

cd client
rm -rf .shadow-cljs/builds/prod || true
shadow-cljs release prod --source-maps --force-spawn
cd ..
