#!/bin/bash
set -eux



profiles=(prod 'test-aws-dev' 'test-aws-prod')
for profile in ${profiles[@]}; do
  cp /data/deployment/sysrev/config/$profile/config.local.edn ./config/$profile/
done

./setup.sh > /dev/null
lein clean
