#!/usr/bin/env bash
set -eux

profiles=('prod' 'test' 'test-aws-dev' 'test-aws-prod')
for profile in ${profiles[@]}; do
  cp /data/deployment/sysrev/config/$profile/config.local.edn ./config/$profile/
done
cp /data/deployment/sysrev/resources/* ./resources/ && true

echo "Checking for linter warnings"

./lint-all
