#!/bin/bash
set -e

if [[ -z "$1" ]]; then
    theme="default"
else
    theme="$1"
fi

set -eu

echo "building semantic (\"$theme\")"

cd semantic/src
rm -f site
ln -s "site.$theme" site
cd ..
rm -rf ./target
# npx gulp clean > /dev/null
npx gulp build-css build-assets > /dev/null
cd ..
out_dir="resources/public/semantic/$theme"
mkdir -p "$out_dir"
rm -rf "$out_dir"

# test that the final output files were created
ls semantic/target/semantic.css > /dev/null
ls semantic/target/semantic.min.css > /dev/null

cp -r semantic/target "$out_dir"

echo "wrote $out_dir"
