#!/usr/bin/env bash
set -eu

rel_out_path="resources/public/css"
abs_out_path="$PWD/$rel_out_path"

ls resources/public > /dev/null
mkdir -p $rel_out_path

cd src/less

rm -f .tmp.css
npx lessc main.less > .tmp.css
mv -f .tmp.css "$abs_out_path/style.default.css"
echo "wrote $rel_out_path/style.default.css"

rm -f .tmp.css
npx lessc main.dark.less > .tmp.css
mv -f .tmp.css "$abs_out_path/style.dark.css"
echo "wrote $rel_out_path/style.dark.css"

cd ../../components

cp -f "org-page/dist/index.css" "$abs_out_path/js-components.css"
echo "Made js-components.css"
