#!/usr/bin/env bash

set -eu

clj-kondo --version > /dev/null || (
  echo "error: clj-kondo not installed"
  echo
  echo "Source:"
  echo "https://github.com/borkdude/clj-kondo"
  echo
  echo "Using npm:"
  echo "npm install -g clj-kondo"
  echo
  exit 1
)

which shadow-cljs > /dev/null || (
  echo "error: shadow-cljs not installed"
  echo
  echo "Using npm:"
  echo "npm install -g shadow-cljs"
  echo
  exit 1
)

cpath_server=$(lein with-profile +test classpath)
cd client
cpath_client=$(shadow-cljs classpath)
cd ..

clj_kondo_quiet() {
  classpath="$@"
  clj-kondo --parallel --lint $classpath | grep -v 'warning:' | grep -v 'error:' || true
}

echo "processing CLJ project ..."
clj_kondo_quiet $cpath_server
echo "processing CLJS project ..."
cd client ; clj_kondo_quiet $cpath_client ; cd ..
