#!/usr/bin/env bash

ready=1

if [ -z "$AWS_ACCESS_KEY_ID" ]; then
  echo >&2 "AWS_ACCESS_KEY_ID not set"
  ready=0
fi
if [ -z "$AWS_SECRET_ACCESS_KEY" ]; then
  echo >&2 "AWS_SECRET_ACCESS_KEY not set"
  ready=0
fi

if [ "$ready" -eq 0 ]; then
  echo >&2 "Missing required AWS credentials from environment"
  exit 1
fi
