#!/usr/bin/env bash
set -e

if [[ -z "$SYSREV_REBUILD" ]]; then
    SYSREV_REBUILD="1"
fi

set -eu

if [[ $SYSREV_REBUILD == "1" ]]; then
    lein build-prod
    mv ./target/sysrev-web-0.1.0-SNAPSHOT-standalone.jar .
fi

scp ./sysrev-web-0.1.0-SNAPSHOT-standalone.jar ubuntu@"$SYSREV_HOST":/data/sysrev/sysrev-web-standalone.jar
ssh ubuntu@"$SYSREV_HOST" "bash /data/sysrev/scripts/receive-server"

rm -f deploy-done.server
touch deploy-done.server
scp ./deploy-done.server ubuntu@"$SYSREV_HOST":/data/sysrev/deploy
rm -f deploy-done.server
