#!/bin/bash
set -eu

echo $SYSREV_HOST > /dev/null

dir=`pwd`

mkdir -p $dir/deploy
rm -f $dir/deploy/client.tgz

lein cljsbuild once production

cd ./resources/public

mkdir tmp
cp -R ./out-production ./tmp/out
cp ./ga.js ./tmp/ga.js
cp -R ./css/ ./tmp/
cp ./favicon.ico ./tmp
cp -R ./semantic ./tmp
cp -R  ./vendor ./tmp
cd tmp
tar -czf $dir/deploy/client.tgz *
cd ..
rm -rf ./tmp

cd $dir

scp ./deploy/client.tgz ubuntu@"$SYSREV_HOST":/data/sysrev/deploy

rm -f deploy-done.client
touch deploy-done.client
scp ./deploy-done.client ubuntu@"$SYSREV_HOST":/data/sysrev/deploy
rm -f deploy-done.client
