#!/bin/bash
set -e

if [[ -z "$SYSREV_REBUILD" ]]; then
    SYSREV_REBUILD="1"
fi

set -eu

echo $SYSREV_HOST > /dev/null

dir=`pwd`

mkdir -p $dir/deploy
rm -f $dir/deploy/client.tgz

if [[ $SYSREV_REBUILD == "1" ]]; then
    lein cljsbuild once production
fi

cd ./resources/public

mkdir tmp
cp -R ./out-production ./tmp/out
cp ./ga.js ./tmp/ga.js
cp -R ./css/ ./tmp/
cp ./favicon.ico ./tmp
cp -R ./semantic ./tmp
cd tmp
tar -czf $dir/deploy/client.tgz *
cd ..
rm -rf ./tmp

cd $dir

scp ./deploy/client.tgz ubuntu@"$SYSREV_HOST":/data/sysrev/deploy

rm -f deploy-done.client
touch deploy-done.client
scp ./deploy-done.client ubuntu@"$SYSREV_HOST":/data/sysrev/deploy
rm -f deploy-done.client
