#!/bin/bash
set -e

if [[ -z "$SYSREV_REBUILD" ]]; then
    SYSREV_REBUILD="1"
fi

set -eu

echo $SYSREV_HOST > /dev/null

dir=`pwd`

mkdir -p $dir/deploy
rm -f $dir/deploy/client.tgz

if [[ $SYSREV_REBUILD == "1" ]]; then
    cd client
    rm -rf .shadow-cljs/builds/prod || true
    shadow-cljs release prod --source-maps --force-spawn
    cd ..

    ./scripts/build-css
fi

cd ./resources/public

rm -rf ./tmp
mkdir tmp
cp -R ./out-production ./tmp/out
cp *.js ./tmp
cp -R ./css/ ./tmp/
cp -R ./semantic ./tmp

# favicon and image files
cp ./favicon.ico ./tmp
cp ./*.png ./tmp
cp -R ./images/ ./tmp/
cp ./manifest.json ./tmp

# crawler config files
cp ./robots.txt.* ./tmp
cp ./sitemap.* ./tmp

# pdfjs (pdf.worker.min.js for react-pdf)
pdfjs_src="${dir}/client/node_modules/pdfjs-dist/build"
pdfjs_dest="./tmp/js/pdfjs-dist/build"
mkdir -p $pdfjs_dest
cp -r $pdfjs_src/* $pdfjs_dest/

cd tmp
tar -czf $dir/deploy/client.tgz *
cd ..
rm -rf ./tmp

cd $dir

scp ./deploy/client.tgz ubuntu@"$SYSREV_HOST":/data/sysrev/deploy

rm -f deploy-done.client
touch deploy-done.client
scp ./deploy-done.client ubuntu@"$SYSREV_HOST":/data/sysrev/deploy
rm -f deploy-done.client
