#!/bin/bash
set -eu
cd client
input_paths="src node_modules semantic package.json package-lock.json shadow-cljs.edn"
output_path="resources/public/out-production/sysrev.js"
if [ ! -f "$output_path" ] ; then
  echo "! $output_path"
else
  find -L $input_paths -cnewer "$output_path"
fi
