#!/bin/bash
set -eu

if [[ -e "./flyway" ]]; then
    echo "flyway is already installed"
    exit
fi

rm -f flyway
rm -rf flyway-4.0.1
rm -f flyway-commandline-4.0.1.tar.gz

echo "Downloading and installing Flyway..."
wget https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/4.0.1/flyway-commandline-4.0.1.tar.gz
tar zxf flyway-commandline-4.0.1.tar.gz
ln -s flyway-4.0.1/flyway flyway
rm -f flyway-commandline-4.0.1.tar.gz
cp flyway.conf.example flyway.conf

echo "Flyway installed."
echo " ** ./flyway script created"
echo " ** SQL schema files are in ./resources/sql"
echo " ** Edit Flyway config at ./flyway.conf (copied from flyway.conf.example)"
