#!/usr/bin/env bash

arg="$1"
if [ "$arg" == "reinstall" ]; then
  reinstall=1
else
  reinstall=0
fi

set -eu

pwd="$(pwd)"

if [ "$reinstall" == "1" ]; then
  echo "deleting installed semantic files"
  rm -rf node_modules
  rm -rf semantic
  git checkout -- semantic
fi

cmd="npm i fomantic-ui --ignore-scripts --no-save"
echo "running: $cmd" && $cmd >/dev/null
cmd="npm i --no-save"
echo "running: $cmd" && $cmd >/dev/null

f="node_modules/fomantic-ui/tasks/install.js"
echo "disable auto-build: modifying file $f"
mv -f "$f" "$f.backup"
sed -Ee s/'(.* )(gulp\.series.*build.*callback\).*)'/'\1\/\/\2'/ "$f.backup" >"$f"
cat "$f" | grep "//gulp.series('build')(callback);" >/dev/null

echo "running: gulp install"
cd "$pwd"/node_modules/fomantic-ui
npx gulp install >/dev/null || true
cd "$pwd"
