#!/usr/bin/env bash
set -eu -o pipefail ; S="./scripts"

if [[ -e "./flyway" ]]; then
  echo "flyway is already installed"
  exit
fi

v="8.2.0"

rm -f flyway
rm -rf .flyway-*.* 2> /dev/null
rm -f flyway-commandline-*.tar.gz 2> /dev/null

echo -n "Downloading and installing Flyway... "
wget --quiet https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/$v/flyway-commandline-$v.tar.gz
tar zxf flyway-commandline-$v.tar.gz
mv flyway-$v .flyway-$v
ln -s .flyway-$v/flyway flyway
rm -f flyway-commandline-$v.tar.gz
cp flyway.conf.example flyway.conf
echo -e "done\n"

(echo "./flyway script created"
 echo "SQL schema files are in ./resources/sql"
 echo "Edit Flyway config at ./flyway.conf (copied from flyway.conf.example)") |
  $S/prefix-lines - " * " ; echo
