#!/bin/bash
set -e

if [[ -z "$SYSREV_HOST" ]]; then
    host="localhost"
else
    host="$SYSREV_HOST"
fi

set -eu

port=$SYSREV_PORT
db=$SYSREV_DB

date_string=$(date +%F_%H-%M-%S)
fname="sysrev-pull-${date_string}.pgdumpc"
options="-T article_similarity -T schema_version"

(>&2 echo "pulling from $host:$port/$db to file $fname")

cmd="pg_dump -h $host -p $port -U postgres -Fc $options $db"
$cmd > $fname
echo "$fname"
