#!/usr/bin/env bash
set -eu

sync_package_json () {
    if [ -z "${CI:-}" ] && [ ! -z "$(find -L package.json -cnewer package-lock.json)" ]; then
        npm install --package-lock-only
    fi

    if [ ! -d "node_modules" ] || [ ! -z "$(find -L package-lock.json -cnewer node_modules)" ]; then
        npm ci
    fi
}

changes="$(scripts/find-client-changes)"

cd client

sync_package_json;

if [ ! -z "$changes" ] ; then
    echo "Found client changes:"
    echo -e "$(echo "$changes" | head -n100)\n"
    echo -e "Rebuilding client code...\n"
    npx -y shadow-cljs release prod --force-spawn
    cd ..
else
    echo "Client code not changed"
fi
