#!/usr/bin/env bash
set -eu

root="$PWD"
client="$root/client"

sync_package_json() {
  if [ -z "${CI:-}" ] && [ -n "$(find -L package.json -cnewer package-lock.json)" ]; then
    npm install --package-lock-only
  fi

  if [ ! -d "node_modules" ] || [ -n "$(find -L package-lock.json -cnewer node_modules)" ]; then
    npm ci
  fi
}

cd "$client"
sync_package_json

changes() {
  cd "$root"
  scripts/find-client-changes
}

if [ -n "$(changes)" ]; then
  echo "Found client changes:"
  changes | head -n100
  echo "Rebuilding client code..."
  cd "$client"
  npx --yes shadow-cljs release prod --force-spawn
else
  echo "Client code not changed"
fi
