#!/bin/bash

set -eu

function env_help {
 echo "SYSREV_PORT and SYSREV_DB must be defined as shell or environment variables, referring to the localhost port number and postgres database name to be reset."
 echo
 echo "Example:"
 echo "SYSREV_PORT=5432 SYSREV_DB=sysrev ./scripts/reset-db"
 exit
}

# Require these vars are set and not empty.
if [ -z ${SYSREV_PORT+x} ] || [ -z ${SYSREV_DB+x} ]; then
    env_help
fi

echo "checking that ./flyway exists..."
ls ./flyway

echo "checking that ./flyway.conf exists..."
ls ./flyway.conf

echo "checking that flyway.conf matches localhost:$SYSREV_PORT/$SYSREV_DB..."
grep -E ".*localhost:$SYSREV_PORT/$SYSREV_DB\$" flyway.conf

echo "dropping database (if exists)..."
dropdb -h localhost -p $SYSREV_PORT -U postgres $SYSREV_DB || true

echo "creating database..."
createdb -h localhost -p $SYSREV_PORT -U postgres -T template0 $SYSREV_DB

echo "running flyway migrations..."
./flyway migrate > /dev/null
