#!/bin/bash

set -eu

fname="$SR_BACKUP_FILE"

opts=( '--disable-triggers'
       '--single-transaction'
       "--dbname=$SR_DEST_DB"
       '--format=custom'
       '--no-owner'
       '--username=postgres'
       '--host=localhost'
       "--port=$SR_DEST_PORT"
       '--no-password')

opts=$(printf " %s" "${opts[@]}")
opts=${opts:1}

readonly_user="readaccess"

psql -U postgres postgres --list > /dev/null

psql -U $readonly_user postgres --list > /dev/null || (
    echo "postgres user \"$readonly_user\" is required"
    echo "run to create: \"createuser -U postgres $readonly_user\""
    false
)

echo "dropping database (if exists)..."
dropdb -h localhost -p $SR_DEST_PORT -U postgres $SR_DEST_DB || true

echo "creating database..."
createdb -h localhost -p $SR_DEST_PORT -U postgres -T template0 $SR_DEST_DB

echo "running pg_restore..."

set -x
time pg_restore $opts $fname
