#!/usr/bin/env bash
set -eux

lein eastwood "{:source-paths [\"src/clj\" \"src/cljc\"] :namespaces [:source-paths] :exclude-namespaces [sysrev.user sysrev.browser-test-main] :exclude-linters [:constant-test #_ :unlimited-use]}"
