#!/usr/bin/env bash
set -eu

source vars.sh

compile=true
test_id=''

# https://stackoverflow.com/questions/7069682/how-to-get-arguments-with-flags-in-bash/21128172
print_usage() {
    echo "test-local - run tests locally"
    echo " "
    echo "options:"
    echo "-h  show this help section"
    echo "-c  when false, don't compile clojurescript before testing. defaults to true"
    echo "-n  a single namespace or var to test. runs all tests when blank"
}

while getopts 'hc:n:' flag; do
    case "${flag}" in
	h) print_usage
	   exit 1;;
	c) compile="${OPTARG}" ;;
	n) test_id="${OPTARG}" ;;
	*) print_usage
	   exit 1 ;;
    esac
done

scripts/build-css

if [ $compile = true ]; then
    cd client
    npx shadow-cljs release prod
    cd ..
fi

if [ -z $test_id ]; then
    ENV=test time clj -T:build run-tests
else
    ENV=test time clj -T:build run-tests :focus :$test_id
fi
