#!/bin/bash
set -eu

export PATH=$PWD/scripts/:$PATH

source vars.sh

changes="$(find-client-changes)"
if [ ! -z "$changes" ] ; then
  echo "Found client changes:"
  echo -e "$(echo "$changes" | head -n100)\n"
  echo -e "Rebuilding client code...\n"
  cd client
  npx shadow-cljs release prod
  cd ..
else
  echo "Client code not changed"
fi

lint_passed=0
./lint-all && lint_passed=1

tests_passed=0
time lein run-tests && tests_passed=1
echo

if [ "$tests_passed" == "0" ] ; then
  echo "!! tests failed"
fi
if [ "$lint_passed" == "0" ] ; then
  echo "!! linter warnings from clj-kondo"
fi

if [[ "$tests_passed" == "1" && "$lint_passed" == "1" ]] ; then
  exit 0
else
  exit 1
fi
