#!/usr/bin/env bash
set -eu

scripts/check-secrets

test_id=''

# https://stackoverflow.com/questions/7069682/how-to-get-arguments-with-flags-in-bash/21128172
print_usage() {
  echo "test-local - run tests locally"
  echo " "
  echo "options:"
  echo "-h  show this help section"
  echo "-n  a single namespace or var to test. runs all tests when blank"
}

while getopts 'hc:n:' flag; do
  case "${flag}" in
    h)
      print_usage
      exit 1
      ;;
    n) test_id="${OPTARG}" ;;
    *)
      print_usage
      exit 1
      ;;
  esac
done

scripts/rebuild-changed-files
scripts/rebuild-cljs-prod

run_tests() {
  ENV="test" time clj -T:build run-tests "$@"
}

if [ -z "$test_id" ]; then
  run_tests
else
  run_tests :focus :"$test_id"
fi
