#!/usr/bin/env bash
set -eu

source vars.sh

compile=true
namespace=''

# https://stackoverflow.com/questions/7069682/how-to-get-arguments-with-flags-in-bash/21128172
print_usage() {
    echo "test-local - run tests locally"
    echo " "
    echo "options:"
    echo "-h  show this help section"
    echo "-c  when false, don't compile clojurescript before testing. defaults to true"
    echo "-n  a single namespace to test, defaults to all of them"
}

while getopts 'hc:n:' flag; do
    case "${flag}" in
	h) print_usage
	   exit 1;;
	c) compile="${OPTARG}" ;;
	n) namespace="${OPTARG}" ;;
	*) print_usage
	   exit 1 ;;
    esac
done

scripts/build-css

if [ $compile = true ]; then
    cd client
    npx shadow-cljs release prod
    cd ..
fi

if [ -z $namespace ]; then
    ENV=test time lein with-profile +postgres eftest
else
    ENV=test time lein with-profile +postgres eftest $namespace
fi
