CITATIONS = <[ WHITESPACE ]> CITATION+
CITATION = LINE+ <END_CITATION> <WHITESPACE>
<END_CITATION> = END_RECORD_TAG CARRIAGE_RETURN
END_RECORD_TAG = "ER  - "
LINE = TAG VALUE
<TAG> = TAG_NAME TAG_DELIM
TAG_NAME = #"[A-Z,0-9]{2}"
<TAG_DELIM> = <"  -">
<VALUE> = VAL_DELIM VAL CARRIAGE_RETURN
<VAL_DELIM> = <" ">
<CARRIAGE_RETURN>= <"\r">
VAL = #"(?s)^((?!\r).)*" (* see: https://stackoverflow.com/questions/406230/regular-expression-to-match-a-line-that-doesnt-contain-a-word *)
<WHITESPACE> = #"(\r)*"
