name: "Test Nix build on macOS"

on:
  push:
    paths:
      - '.github/workflows/macos-nix.yml'
      - '**.nix'
      - '**/flake.lock'

jobs:
  nix:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixpkgs-22.11-darwin

      - name: Restore cached Nix store
        id: nix-cache-restore
        uses: john-shaffer/cache/restore@main
        with:
          key: nix-${{ github.repository }}-${{ runner.os }}-${{ hashFiles('**.nix', '**/flake.lock') }}
          restore-keys: |
            nix-${{ github.repository }}-${{ runner.os }}-
          path: |
            /nix/store
            /nix/var/nix/db/db.sqlite

      - name: Build Nix derivations
        if: steps.nix-cache-restore.outputs.cache-hit != 'true'
        run: |
          nix develop -c echo OK
      - name: Save cached Nix store

        if: steps.nix-cache-restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v3
        with:
          key: nix-${{ github.repository }}-${{ runner.os }}-${{ hashFiles('**.nix', '**/flake.lock') }}
          path: |
            /nix/store
            /nix/var/nix/db/db.sqlite

      - name: Test nix devShell
        run: |
          nix develop -c clj -P

      - name: Log job run to Slack
        uses: 8398a7/action-slack@v3.14.0
        if: always()
        with:
          status: custom
          fields: workflow,job,commit,repo,ref,author,took
          custom_payload: |
            {
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                text: `${process.env.AS_WORKFLOW}\n${process.env.AS_JOB} (${process.env.AS_COMMIT}) of ${process.env.AS_REPO}@${process.env.AS_REF} by ${process.env.AS_AUTHOR} ${{ job.status }} in ${process.env.AS_TOOK}`,
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
