name: "Test Nix build on macOS"

on:
  push:
    paths:
      - '.github/workflows/macos-nix.yml'
      - '**.nix'

jobs:
  nix:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixpkgs-21.11-darwin

      - name: Build Nix derivation
        run: |
          mkdir -p ~/.config/nixpkgs
          echo "{ allowUnfree = true; }" > ~/.config/nixpkgs/config.nix
          nix-build -A inputDerivation -o gcroots

      - name: Test nix-shell
        run: |
          nix-shell --pure --run "echo 0 | clj-kondo --lint -"

      - name: Log job run to Slack
        uses: 8398a7/action-slack@v3.13.0
        if: always()
        with:
          status: custom
          fields: workflow,job,commit,repo,ref,author,took
          custom_payload: |
            {
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                text: `${process.env.AS_WORKFLOW}\n${process.env.AS_JOB} (${process.env.AS_COMMIT}) of ${process.env.AS_REPO}@${process.env.AS_REF} by ${process.env.AS_AUTHOR} ${{ job.status }} in ${process.env.AS_TOOK}`,
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
